apiVersion: apps/v1
kind: Deployment
metadata:
  name: confeitei-api
  namespace: production
spec:
  selector:
    matchLabels:
      app: confeitei-api
  template:
    metadata:
      labels:
        app: confeitei-api
    spec:
      containers:
      - name: confeitei-api
        image: clue/json-server:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: confeitei-api-service
  namespace: production
spec:
  selector:
    app: confeitei-api
  ports:
  - port: 80
    targetPort: 80
