apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
type: Opaque
data:
  DRONE_GITHUB_CLIENT_ID: xxxxxxx     # Get this from GitHub OAUTH
  DRONE_GITHUB_CLIENT_SECRET: xxxxxxx # Get this from GitHub OAUTH
  DRONE_RPC_SECRET: xxxxxxx           # openssl rand -hex 16
  DRONE_USER_CREATE: xxxxxxx          # username:marcel-dempers,admin:true
  DRONE_SERVER_HOST: xxxxxxx          # drone.marceldempers.dev
  DRONE_DATABASE_DRIVER: xxxxxxx      # ex: postgres
  DRONE_DATABASE_DATASOURCE: xxxxxxx  # ex: postgres://alex:endpoint=ep-cool-darkness-123456;AbC123dEf@ep-cool-darkness-123456.us-east-2.aws.neon.tech/dbname?sslmode=require