apiVersion: apps/v1
kind: Deployment
metadata:
  name: nignx
  namespace: production
spec:
  selector:
    matchLabels:
      app: nignx
  template:
    metadata:
      labels:
        app: nignx
    spec:
      containers:
      - name: nignx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  namespace: production
spec:
  selector:
    app: nignx
  ports:
  - port: 80
    targetPort: 80