apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app
spec:
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
      - name: devops-app
        image: kub3dev/devops-app:2024.7.9.20.11.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: devops-app-server
spec:
  selector:
    app: devops-app
  ports:
  - port: 80
    targetPort: 8080

