apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: confeitei.app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kub3dev/devops.git
    targetRevision: HEAD
    path: apps/production/confeitei
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true