apiVersion: apps/v1
kind: Deployment
metadata:
  name: picpay
spec:
  selector:
    matchLabels:
      app: picpay
  template:
    metadata:
      labels:
        app: picpay
    spec:
      containers:
      - name: picpay
        image: kub3dev/picpay-desafio-backend:2024.7.9.20.11.16
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: picpay-server
spec:
  selector:
    app: picpay
  ports:
  - port: 80
    targetPort: 8080

